name = "testReg"
uuid = "0ba7cd0e-ef51-4802-bf36-7a24fcb011b1"
repo = "https://github.com/SaveIssac/JuliaRegistry.git"
description = "test"

[packages]
9b4b8fa1-9ac0-43e7-a9e8-87f92f8c98fa = { name = "testPkg", path = "T/testPkg" }
